services:
  express:
    container_name: express
    build:
      context: ./express
      dockerfile: Dockerfile
      target: builder
    ports:
      - ${EXPRESS_PORT}:3000
    depends_on:
      - db
    tty: true
    volumes:
      - ./express:/app
    networks:
      app-network:
        ipv4_address: ${EXPRESS_IP}
  db:
    container_name: db
    build: ./db
    ports:
      - ${DB_PORT}:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        ipv4_address: ${DB_IP}
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
      target: builder
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - express
    tty: true
    volumes:
      - ./front:/app
    networks:
      app-network:
        ipv4_address: ${FRONT_IP}

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
